# Generated by Django 2.2.24 on 2022-03-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Nom')),
                ('Description', models.TextField(max_length=800, verbose_name='Description du tache')),
                ('StartDate', models.DateField(max_length=100, verbose_name='Date de début')),
                ('EndDate', models.DateField(max_length=100, verbose_name='Date de fin')),
                ('Statut', models.CharField(max_length=100, verbose_name='Statut du tache')),
            ],
        ),
    ]
