# Generated by Django 2.2.24 on 2022-03-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
        ('Taches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.Project'),
        ),
    ]
