# Generated by Django 2.2.24 on 2022-03-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0002_tache_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='Statut',
        ),
        migrations.AddField(
            model_name='tache',
            name='Status',
            field=models.CharField(choices=[('Complete Tache', 'Complete Tache'), ('Incomplete Tache ', 'Incomplete Tache')], max_length=200, null=True),
        ),
    ]
