# Generated by Django 2.2.24 on 2022-03-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0004_auto_20220328_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='Status',
            field=models.CharField(choices=[('uncompleted', 'uncompleted'), ('complete', 'complete')], max_length=200, null=True),
        ),
    ]
