# Generated by Django 2.2.24 on 2022-04-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0006_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='Status',
            field=models.CharField(choices=[('uncompleted', 'uncompleted'), ('completed', 'completed')], max_length=200, null=True),
        ),
    ]
