# Generated by Django 2.2.24 on 2022-04-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0007_auto_20220417_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='Description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='tache',
            name='EndDate',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tache',
            name='StartDate',
            field=models.DateField(max_length=100),
        ),
    ]
