# Generated by Django 2.2.24 on 2022-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0008_auto_20220417_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='Status',
            field=models.CharField(choices=[('uncompleted', 'uncompleted'), ('completed', 'completed')], default='uncompleted', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Affectation',
        ),
    ]
