# Generated by Django 2.2.24 on 2022-03-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete')], max_length=200, null=True),
        ),
    ]
