# Generated by Django 2.2.24 on 2022-04-11 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20220331_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='project',
            name='EndDate',
            field=models.DateField(max_length=100, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectManager',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='StartDate',
            field=models.DateField(max_length=100, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('uncompleted', 'uncompleted'), ('completed', 'completed')], default='uncompleted', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Title',
            field=models.CharField(max_length=255),
        ),
    ]
