# Generated by Django 2.2.24 on 2022-04-12 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20220411_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ProjectManager',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
    ]
