# Generated by Django 2.2.24 on 2022-04-12 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20220412_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ProjectManager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
    ]
