# Generated by Django 2.2.24 on 2022-03-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('1', 'Chef Du Projet'), ('2', 'Utilisateur'), ('3', 'Client')], max_length=100),
        ),
    ]
