# Generated by Django 2.2.24 on 2022-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20220320_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('1', 'Chef Du Projet'), ('2', 'Employee'), ('3', 'Client')], max_length=100),
        ),
    ]
